### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dnkls** [lolwaleet/ReverseIP#1]
After install and start with domain or ip i see this 

```
/root/ReverseIP/revIP.rb:51:in `+': no implicit conversion of nil into String (TypeError)
from /root/ReverseIP/revIP.rb:51:in `<main>'

```

**Comment by ottmon** [comment]
Same problem like 	dnkls

**Comment by Imanfeng** [comment]
revIP.rb:51:in `+': no implicit conversion of nil into String (TypeError)
	from revIP.rb:51:in `<main>'

**Comment by lolwaleet** [comment]
Fixed!
